version: '3'

services:
  zipcode-search:
    container_name: zipcode-search
    env_file:
      - .env
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/zipcode-search
    command: ["revel", "run", "-a", "zipcode-search"]